[package]
name = "APS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { version = "0.15.0", features = ["rayon"] }
ndarray-rand = "0.14.0"
thiserror = "1.0"

[lib]
doctest = false
